config/routes.rb
ForkStackoverflow::Application.routes.draw do

  devise_for :users

  resources :questions do
    member do
      put :positive_vote
      put :negative_vote
    end
    resources :answers do
      member do
        put :positive_vote
        put :negative_vote
      end
    end
  end

  root :to => "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  def positive_vote!
    update_attribute(:positive_vote, positive_vote+1)
  end

  def negative_vote!
    update_attribute(:negative_vote, negative_vote+1)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :user

  def positive_vote!
    update_attribute(:positive_vote, positive_vote+1)
  end

  def negative_vote!
    update_attribute(:negative_vote, negative_vote+1)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :confirmable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation


  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]

  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  def positive_vote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.positive_vote!
    redirect_to(@question, :notice => 'Voto positivo')
  end

  def negative_vote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.negative_vote!
    redirect_to(@question, :notice => 'Voto negativo')
  end


  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(params[:answer])
    @answer.user = current_user
    if @answer.save
      redirect_to(@question, :notice => 'La respuesta ha sido publicada.')
    else
      render :action => "new"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]

  def index
    @questions = Question.order("created_at desc").limit(50)
  end

  def new
    @question = current_user.questions.build
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.build
  end

  def positive_vote
    @question = Question.find(params[:id])
    @question.positive_vote!
    redirect_to(@question, :notice => 'Voto positivo')
  end

  def negative_vote
    @question = Question.find(params[:id])
    @question.negative_vote!
    redirect_to(@question, :notice => 'Voto negativo')
  end


  def create
    @question = current_user.questions.build(params[:question])
    if @question.save
        redirect_to(@question, :notice => 'La pregunta ha sido publicada.')
      else
        render :action => "new"
      end
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def user_from_email(email)
    email.gsub(/(@.*)/, "")
  end
end

app/views/answers/_form.erb
<%= form_for [@question, @answer] do |form| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> El formulario tiene un error:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %><br />
    <%= form.text_area :body %> <br />
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/new.html.erb
<h1 class="title">send a new answer</h1><br />

<div class="content"><%= render 'form' %></div><br />

<%= link_to 'Back', questions_path %>

app/views/answers/show.html.erb
<h1 class="title">Show answers</h1><br />
<p id="notice"><%= notice %></p>




<p class="content">
  <%=  @answers.body %>
  <%=  @answers.user %>

</p><br />

<%= link_to 'Back', questions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title >ForkStackoverflow</title>
  <%= stylesheet_link_tag    "reset", "grid", "base" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
  <body>
    <!-- .wrapper -->
    <div class="wrapper">
      <!-- .container -->
      <div class="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Te has logeado con la cuenta <%= current_user.email %>. no eres tu?
          <%= link_to "Salir", destroy_user_session_path %>
        <% else %>
          <%= link_to "Registrarse", new_user_registration_path %> o <%= link_to "logearse", new_user_session_path %>
        <% end %>
      </div><br/>
        <div class="header row">
          <div class="four columns">
            <h1 id="title"  >Fork Stack Overflow</h1>
          </div>
        </div>

        <div class="flashes">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>

        <%= yield %>
        <!-- .footer -->
        <div class="footer">
          site design / logo © 2010 stack overflow internet services, inc; user contributions licensed under cc-wiki with attribution required
        </div><!-- .footer -->
      </div><!-- .container -->
    </div><!-- .wrapper -->
  </body>
</html>

app/views/questions/_form.erb
<%= form_for(@question) do |form| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> El formulario tiene un error:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %><br />
    <%= form.text_area :question %> <br />

  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/index.html.erb
<h1 class="title" >Question index</h1><br />
<ul>

<% @questions.each do |question| %>
  <li>
    <div class="two columns"><%= time_ago_in_words(question.created_at) %></div>
    <div class="nine columns"> <%= link_to question.question, question %></div>
    <div class="two columns"><%=  question.user %></div><br /><br />


  </li>
<% end %>
</ul> <br />
<% if user_signed_in? %>
<%= link_to 'New Question', new_question_path %>
<% end %>

app/views/questions/new.html.erb
<h1 class="title">Question new</h1><br />



<% if user_signed_in? %>
<div id="new-log-entry-box"><%= render 'form' %></div><br />
<% end %>



<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h1 class="title">Question show</h1><br />

<ul class="list">
  <li class="content row" >
    <div class="one columns"><%= time_ago_in_words(@question.created_at) %></div>
    <div class="thirteen columns"><%=  @question.question %></div>
    <div class="two columns"><%=  user_from_email(@question.user.email) %></div><br/><br/>
    <div class="two columns">
      <label class="green"><%= @question.positive_vote %></label>  |
      <label class="red"><%= @question.negative_vote %></label>
    </div><br />
    <br />

    <% if user_signed_in? %>
    <div class="two columns">
      <%= link_to image_tag("vote-arrow-up-on.png") , [:positive_vote, @question], :method => :put %>
      <%= link_to image_tag("vote-arrow-down-on.png") , [:negative_vote, @question], :method => :put %>
    </div>
    <% end -%>
  </li>
</ul><br />

<ul class="list">
      <li class="item highlight row">
        <div class="thirteen columns">Creado el</div>
        <div class="thirteen columns">Respuesta</div>
        <div class="two columns">Usuario</div>
        <span class="divider"></span>
      </li><br/>
  <% @question.answers.each do |answer| %>
      <% next if answer.new_record? %>
      <li class="item row">

        <div class="two columns"><%= time_ago_in_words(answer.created_at) %></div>
        <div class="thirteen columns">
          <%= answer.body %>
        </div>
        <div class="two columns">
        <%= user_from_email(answer.user.email) %>
        </div><br/><br/>
        <div class="two columns">
          <label class="green"><%= answer.positive_vote %></label>  |
          <label class="red"><%= answer.negative_vote %></label>
        </div><br />
        <br />


        <% if user_signed_in? -%>
       <div class="two columns">
        <%= link_to image_tag("vote-arrow-up-on.png") , [:positive_vote, @question, answer], :method => :put %>
        <%= link_to image_tag("vote-arrow-down-on.png") , [:negative_vote, @question, answer], :method =>  :put %>
      </div>
      <% end -%>

      </li><br/>
  <% end %>
</ul>
<% if user_signed_in? %>
<div id="new-log-entry-box"><%= render 'answers/form' %></div><br />
<% else %>
<%= link_to "Publica tu respuesta", new_user_session_path %><br/><br/>

<% end %>
<%= link_to 'Back', questions_path %>